-- Core schema: users, events (series), occurrences (single firings).
-- Terminology: "occurrence" = the initial scheduled notification act,
-- "reminder" = a repeat notification while the occurrence stays OPEN.

create table app_user (
    id               bigint generated by default as identity primary key,
    telegram_chat_id bigint      not null unique,
    timezone         varchar(64) not null,
    work_start       time        not null default time '09:00',
    work_end         time        not null default time '22:00',
    created_at       timestamptz not null default now()
);

create table event (
    id                   bigint generated by default as identity primary key,
    user_id              bigint       not null references app_user (id),
    name                 varchar(255) not null,
    status               varchar(16)  not null,
    schedule_type        varchar(32)  not null,
    interval_minutes     integer,
    time_of_day          time,
    days_of_week         varchar(16),
    first_fire_at        timestamptz,
    nag_interval_minutes integer,
    next_fire_at         timestamptz,
    created_at           timestamptz  not null default now()
);

create index idx_event_due on event (next_fire_at) where status = 'ACTIVE';

create table occurrence (
    id                  bigint generated by default as identity primary key,
    event_id            bigint      not null references event (id),
    fired_at            timestamptz not null,
    status              varchar(16) not null,
    next_reminder_at    timestamptz,
    done_at             timestamptz,
    telegram_message_id bigint,
    created_at          timestamptz not null default now()
);

-- "no debt" invariant: at most one open occurrence per event
create unique index uq_occurrence_open_per_event on occurrence (event_id) where status = 'OPEN';
create index idx_occurrence_reminder_due on occurrence (next_reminder_at) where status = 'OPEN';
